import Head from "next/head";
import dynamic from "next/dynamic";
import React, { useState } from "react";
import { Box, VStack } from "@chakra-ui/layout";
import { Button } from "@chakra-ui/button";

const colors = [
  "#000080", // dark blue
  "#0000b3",
  "#0000cc",
  "#0000e6",
  "#0000ff",
  "#4d4dff",
  "#9999ff",
  "#b3b3ff",
  "#ccccff",
  "#e6e6ff",
  "#ffffff",
  "#e6e6ff",
  "#ccccff",
];
const data = [
  {
    option: "Fancy Olive Oil",
    style: { textColor: "white" },
  },
  {
    option: "$100 Gift Card",
    style: { textColor: "white" },
  },
  {
    option: "2 movie dates",
    style: { textColor: "white" },
  },
  {
    option: "Wine or Beer Subscription",
    style: { textColor: "white" },
  },
  {
    option: "1 home cooked meal",
    style: { textColor: "white" },
  },
  {
    option: "$200 Airbnb Gift Card",
  },
  {
    option: "Fancy Olive Oil",
  },
  {
    option: "1 home cooked meal",
  },
  {
    option: "Train ticket & broadway",
  },
  {
    option: "1 home cooked meal",
  },
  {
    option: "Car oil change",
  },
  {
    option: "$200 gift card",
  },
  {
    option: "Coffee subscription",
  },
];

const Wheel = dynamic(
  () => import("react-custom-roulette").then((mod) => mod.Wheel),
  { ssr: false }
);

export default function Home() {
  const [mustSpin, setMustSpin] = useState(false);
  const [prizeNumber, setPrizeNumber] = useState(0);
  const [spinsRemaining, setSpinsRemaining] = useState(3);

  const handleSpinClick = () => {
    if (spinsRemaining === 0) {
      alert("No more spins!");
      return;
    }
    const newPrizeNumber = Math.floor(Math.random() * data.length);
    setPrizeNumber(newPrizeNumber);
    setMustSpin(true);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box m={"8px"} paddingTop={"8px"}>
        <VStack spacing={4}>
          <p style={{ fontSize: "32px" }}>Christmas Gift Roulette</p>
          <Wheel
            backgroundColors={colors}
            mustStartSpinning={mustSpin}
            prizeNumber={prizeNumber}
            data={data}
            onStopSpinning={() => {
              setMustSpin(false);
              setSpinsRemaining(spinsRemaining - 1);
            }}
            fontSize={12}
          />
          <Button colorScheme="blue" size="lg" onClick={handleSpinClick}>
            SPIN
          </Button>
          <p style={{ fontSize: "22px" }}>Spins Remaining: {spinsRemaining}</p>
          {prizeNumber && !mustSpin && (
            <p style={{ fontSize: "22px" }}>
              Current Prize: {data[prizeNumber].option}
            </p>
          )}
        </VStack>
      </Box>
    </>
  );
}
